// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ExpectedValue$ReactTemplate = require("./ExpectedValue.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, ExpectedValue$ReactTemplate.make("Coin Flip", 1 / 2, /* array */[])), "app");

/*  Not a pure module */
